# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@5
  inputs:
    cliVersion: 'WIN_24.10.9050.17872'
    cliNupkgPath: 'C:\Users\balamanikanta.krishn\Downloads\UiPath.CLI.25.0.0-dev1\UiPath.CLI.25.0.0-dev1\windows.zip'